version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: RAG
    ports:
      - "5001:5001"  
    volumes:
      - .:/app  
    stdin_open: true  
    tty: true 
    depends_on:
      - ollama  
    environment:
      OLLAMA_HOST: http://ollama:11434

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"  
    volumes:
      - ollama-models:/root/.ollama  
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 5 &&
      while ! ollama list | grep -q 'mistral'; do
        echo 'Model mistral not found. Retrying pull...';
        ollama pull mistral;
        sleep 10;
      done;
      echo 'Model mistral successfully pulled or already present.';
      tail -f /dev/null"


volumes:
  ollama-models:
